DELETE http://localhost:8080/logout
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImZpcnN0TmFtZSI6Im9uZXFmcSIsImxhc3ROYW1lIjoicXdlcmR4ZnN4Y3NmZHNmZHNmZHNmZHNmIiwiZW1haWwiOiJzbXJudmJyczJAZ21haWwuY29tIiwiYXZhdGFyIjoiS2lpZVdqMUsucG5nIiwiaWF0IjoxNjAwOTAwNjc0fQ.48rsFHJeZLoqNbF7Qb-aGvL4F5nV3GurO2t4UlZUDik
{

}

###

PUT http://localhost:3000/api/offers/5
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImlhdCI6MTYwMDgwMjY4OSwiZXhwIjoxNjAwODAyNzA5fQ.s7DNhTWds0K37vzSwoHv3xl7Hv-3L0SYJMUWebbgHLk

{
    "id": 5,
    "title": "Продам новую приставку Sony Playstation 5",
    "picture": "KiieWj1K.png",
    "sum": 1,
    "type": "buy",
    "description": "Продаю с болью в сердце... Это настоящая находка для коллекционера! Пользовались бережно и только по большим праздникам. Бонусом отдам все аксессуары. Если найдёте дешевле — сброшу цену.",
    "category": [1,2,3]
}
###

POST http://localhost:3000/api/user/refresh
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImlhdCI6MTYwMDgwMjI2Mn0.bgRu2SQL8Qrpwy1nkhManqsdg2Xr2eAC2lHR_0KKXI4"
}